all: broadcast-example unicast-sender unicast-receiver sync_node messaging
APPS=servreg-hack
CONTIKI=/home/user/Desktop/contiki
PROJECT_SOURCEFILES += messaging.c
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include

